In [1]:
import pandas as pd

In [2]:
lst=[1,2,3,4,5]
print(lst)

[1, 2, 3, 4, 5]

In [3]:
series = pd.Series(lst)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
a = pd.Series(5,index=["a","b","c","d","e"])
print(a)

a    5
b    5
c    5
d    5
e    5
dtype: int64

In [9]:
b = pd.Series({"a":[1,2,3],"b":[4,5,6],"c":[7,8,9],"d":4,"e":[10,11,12]})
print(b)

a       [1, 2, 3]
b       [4, 5, 6]
c       [7, 8, 9]
d               4
e    [10, 11, 12]
dtype: object

In [10]:
df = pd.DataFrame({"a":[1,2,3],"b":[4,5,6],"c":[7,8,9],"d":4,"e":[10,11,12]},index=["a","b","c"])

   A  B
0  1  4
1  2  5
2  3  6


A     6
B    15
dtype: int64
0    5
1    7
2    9
dtype: int64

In [ ]:
df.tail()

In [26]:
import pandas as pd

df = pd.DataFrame(
    {
        "student_id": [101, 102, 103, 104, 105, 106, 107, 108],
        "name": ["Aarav", "Meera", "Kabir", "Sara", "Ishaan", "Ananya", "Rohit", "Diya"],
        "age": [19, 20, 18, 21, 19, 22, 20, 18],
        "city": ["Delhi", "Mumbai", "Pune", "Delhi", "Bengaluru", "Chennai", "Pune", "Mumbai"],
        "subject": ["Math", "Science", "English", "Math", "Science", "English", "Math", "Science"],
        "score": [88, 76, 91, 64, 85, 73, 95, 82],
        "hours_studied": [10, 8, 12, 5, 9, 7, 13, 11],
        "passed": [True, True, True, True, True, True, True, True],
    }
)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   student_id     8 non-null      int64
 1   name           8 non-null      object
 2   age            8 non-null      int64
 3   city           8 non-null      object
 4   subject        8 non-null      object
 5   score          8 non-null      int64
 6   hours_studied  8 non-null      int64
 7   passed         8 non-null      bool
dtypes: bool(1), int64(4), object(3)
memory usage: 588.0+ bytes

In [28]:
df.describe()

       student_id        age      score  hours_studied
count     8.00000   8.000000   8.000000        8.00000
mean    104.50000  19.625000  81.750000        9.37500
std       2.44949   1.407886  10.250436        2.66927
min     101.00000  18.000000  64.000000        5.00000
25%     102.75000  18.750000  75.250000        7.75000
50%     104.50000  19.500000  83.500000        9.50000
75%     106.25000  20.250000  88.750000       11.25000
max     108.00000  22.000000  95.000000       13.00000

In [29]:
df.size
df.shape
df.columns

Index(['student_id', 'name', 'age', 'city', 'subject', 'score',
       'hours_studied', 'passed'],
      dtype='object')

In [30]:
df.head()

   student_id    name  age       city  subject  score  hours_studied  passed
0         101   Aarav   19      Delhi     Math     88             10    True
1         102   Meera   20     Mumbai  Science     76              8    True
2         103   Kabir   18       Pune  English     91             12    True
3         104    Sara   21      Delhi     Math     64              5    True
4         105  Ishaan   19  Bengaluru  Science     85              9    True

In [31]:
# if you already have df loaded:
df = df.set_index("Sl_number")
# or in-place:
# df.set_index("Sl_number", inplace=True)

# or when reading CSV:
# df = pd.read_csv("file.csv", index_col="Sl_number")

KeyError: "None of ['Sl_number'] are in the columns"

In [24]:
# Working example: use a real column from the current DataFrame
print(df.columns)

if "PassengerId" in df.columns:
    fixed_df = df.set_index("PassengerId")
    print(fixed_df.head())
else:
    print("PassengerId not found. Use one of the columns printed above.")

Index(['student_id', 'name', 'age', 'city', 'subject', 'score',
       'hours_studied', 'passed'],
      dtype='object')
PassengerId not found. Use one of the columns printed above.

In [21]:
df.head()

   student_id    name  age       city  subject  score  hours_studied  passed
0         101   Aarav   19      Delhi     Math     88             10    True
1         102   Meera   20     Mumbai  Science     76              8    True
2         103   Kabir   18       Pune  English     91             12    True
3         104    Sara   21      Delhi     Math     64              5    True
4         105  Ishaan   19  Bengaluru  Science     85              9    True

In [32]:
df.loc[1]

student_id           102
name               Meera
age                   20
city              Mumbai
subject          Science
score                 76
hours_studied          8
passed              True
Name: 1, dtype: object

In [33]:
df.groupby("city")["score"].mean()

city
Bengaluru    85.0
Chennai      73.0
Delhi        76.0
Mumbai       79.0
Pune         93.0
Name: score, dtype: float64

In [34]:
df.groupby("city")["score"].max()

city
Bengaluru    85
Chennai      73
Delhi        88
Mumbai       82
Pune         95
Name: score, dtype: int64

In [35]:
df1 = pd.DataFrame({"rOLL NO.":[1,2,3],"NAME":["A","B","C"]})
df2 = pd.DataFrame({"rOLL NO.":[1,2,3],"MARKS":[85,90,95]})
pd.merge(df1,df2,on="rOLL NO.")

   rOLL NO. NAME  MARKS
0         1    A     85
1         2    B     90
2         3    C     95

In [36]:
pd.merge(df1,df2)

   rOLL NO. NAME  MARKS
0         1    A     85
1         2    B     90
2         3    C     95